;; (setq svg-scratch (svg-create 100 100))
;; (svg-rectangle svg-scratch 25 25 50 50 :id "a")
;; (svg-line svg-scratch 25 25 75 75 :id "b" :stroke-color "black")

;; ;; (svg-remove svg-scratch "a")

;; (insert-image (svg-image (append svg-scratch (nthcdr 2 svg-labels))))

(defun sketch-translate-node-coords (node amount &rest args)
  (dolist (coord args node)
    (cl-decf (alist-get coord (cadr node)) amount)))

(defun svg-translate (dx dy)
  (interactive)
  (mapcar (lambda (node)
            (pcase (car node)
              ('line (sketch-translate-node-coords node dx 'x1 'x2)
                     (sketch-translate-node-coords node dx 'y1 'y2))
              ('rect (sketch-translate-node-coords node dx 'x)
                            (sketch-translate-node-coords node dx 'y))
              ((or 'circle 'ellipse)
               (sketch-translate-node-coords node dx 'cx)
               (sketch-translate-node-coords node dx 'cy))
              ('text (sketch-translate-node-coords node dx 'x)
                     (sketch-translate-node-coords node dx 'y))))
          (cddr svg-sketch)))
